name: Android Build

on:
  push:
    branches: [ "project_updated" ]
  pull_request:
    branches: [ "project_updated" ]

jobs:
  build:
    name: Generate Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate apk
        run:  ./gradlew assembleDebug
        uses: actions/upload-artifact@v1
        with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk


